// generated by svelte-check-native; do not edit
import type { AuthState } from '@nestrum/web/client';
import { onMount } from 'svelte';
import { api, auth, publicConfig } from './nestrum';
function $$render_d6992ac3() {

                                                     
                                 
                                                    

let session = $state<AuthState>({ status: 'loading', user: undefined, error: undefined });
let email = $state('');
let password = $state('');
let failure = $state('');
let apiStatus = $state('not requested');

onMount(() => {
    const stop = auth.state.subscribe((next) => (session = next));
    void auth.refresh();

    return stop;
});

async function signIn(event: SubmitEvent) {
    event.preventDefault();
    failure = '';
    try {
        await auth.signIn({ email, password });
    } catch (error) {
        failure = error instanceof Error ? error.message : 'Sign-in failed.';
    }
}

async function probe() {
    try {
        await api.get('/openapi.json');
        apiStatus = 'ok';
    } catch (error) {
        apiStatus = error instanceof Error ? error.message : 'failed';
    }
}
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("main", {});             { svelteHTML.createElement("h1", {
                "id": `title`,
            });
            }
            { svelteHTML.createElement("p", {
                "id": `site`,
            });
                publicConfig.site ?? 'unset';
            }
            if ((session.status === 'loading')) {
                { svelteHTML.createElement("p", {});                 }
            } else if ((session.status === 'authenticated')) {
                { svelteHTML.createElement("p", {
                    "id": `who`,
                });
                    session.user.email;
                }
                { svelteHTML.createElement("button", {
                    "onclick": (() => auth.signOut()),
                });
                }
            } else {
                { svelteHTML.createElement("form", {
                    "onsubmit": (signIn),
                });
                    { svelteHTML.createElement("input", {
                        "name": `email`,
                        "type": `email`,
                        "bind:value": (email),
                        "placeholder": `Email`,
                    });
                        /*svn:ignore_start*/void (() => { email = __svn_any(null); });/*svn:ignore_end*/
                    }
                    { svelteHTML.createElement("input", {
                        "name": `password`,
                        "type": `password`,
                        "bind:value": (password),
                        "placeholder": `Password`,
                    });
                        /*svn:ignore_start*/void (() => { password = __svn_any(null); });/*svn:ignore_end*/
                    }
                    { svelteHTML.createElement("button", {
                        "type": `submit`,
                    });
                    }
                    if ((failure)) {
                        { svelteHTML.createElement("p", {
                            "role": `alert`,
                        });
                            failure;
                        }
                    }
                }
            }
            { svelteHTML.createElement("button", {
                "onclick": (probe),
            });
            }
            { svelteHTML.createElement("p", {
                "id": `api-status`,
            });
                apiStatus;
            }
        }
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_d6992ac3;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_d6992ac3>>['props'],
    Awaited<ReturnType<typeof $$render_d6992ac3>>['exports'],
    Awaited<ReturnType<typeof $$render_d6992ac3>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;
